# mkdocs.yml
site_name: Calculator
site_url: "https://pages/github/mrc/docs-example/"
repo_url: "https://github/mrc/docs-example/"
docs_dir: mkdocs
site_dir: docs

docs_dir: mkdocs
site_dir: docs

theme:
  name: material

nav:
  - README.md
  - tutorials.md
  - how-to-guides.md
  - explanation.md
  - reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
